# -*- coding: utf-8 -*-
"""agent_langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fd1bMS-nEajhyDW7y4qFapM8ySzgfYY0
"""

!pip install langchain langchain-community openai duckduckgo-search

from langchain.agents import initialize_agent, Tool
from langchain.llms import OpenAI

openai_api_key = "**"

from langchain_community.tools.ddg_search import DuckDuckGoSearchRun

Search_tool = Tool(
    name = "DuckDuckGo Search",
    func=DuckDuckGoSearchRun().run,
    description="useful for when you need to answer questions about current events"
)

agent = initialize_agent(llm=OpenAI(temperature=0, api_key = openai_api_key),
                 tools=[Search_tool],
                 agent="zero-shot-react-description",
                 verbose=True)

response = agent.run("Who won Pak vs India Cricket Match Today(23/2/2025)? What is score of Virat Kohli?")

!pip install wikipedia

from langchain_community.utilities.wikipedia import WikipediaAPIWrapper

wiki_tool = Tool(
    name = "Wikipedia",
    func=WikipediaAPIWrapper().run,
    description="useful for when you need to answer questions about current events"
)

llm=OpenAI(temperature=0, api_key = openai_api_key)

tools = [ wiki_tool]

new_agent = initialize_agent(
                 llm=llm,
                 tools=tools,
                 agent="zero-shot-react-description",
                 verbose=True)

new_agent.run("Who won Narispatnam assembly constituency in 2024 and what is the majority of winner?")

import sqlite3

# Connect to SQLite database (creates example.db if it doesn't exist)
connection = sqlite3.connect("example.db")
cursor = connection.cursor()

# Create the inventory table
cursor.execute("""
CREATE TABLE IF NOT EXISTS inventory (
    id INTEGER PRIMARY KEY,
    product_name TEXT NOT NULL,
    stock_quantity INTEGER NOT NULL
)
""")

# Insert sample data
cursor.executemany("""
INSERT INTO inventory (product_name, stock_quantity) VALUES (?, ?)
""", [
    ("Product A", 150),
    ("Product B", 200),
    ("Product C", 300),
    ("Product D", 100),
    ("Product E", 50)
])

# Commit and close connection
connection.commit()
connection.close()

print("Database created and populated with sample data.")

from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.agent_toolkits.sql.toolkit import SQLDatabaseToolkit

connection = sqlite3.connect("example.db")
cursor = connection.cursor()

cursor.execute("SELECT * FROM inventory WHERE stock_quantity > 100")
rows = cursor.fetchall()

rows

connection.commit()
connection.close()

# Step 1: Connect to the Database
db = SQLDatabase.from_uri("sqlite:///example.db")

# Step 2: Create the SQL Database Toolkit

toolkit = SQLDatabaseToolkit(db=db, llm=llm)

tools = toolkit.get_tools()

tools

len(tools)

tools[0]

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent="zero-shot-react-description",
    verbose=True
)

query1 = "How many units of Product A are in stock?"
response1 = agent.run(query1)
print("Response:", response1)