# -*- coding: utf-8 -*-
"""duckduckgosearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxghoyjGuU6tfKGbKJuWqaD68t14GKi8
"""

!pip install --upgrade langchain langchain-community langgraph openai langchain_openai

!pip install duckduckgo-search

from langchain_community.tools import DuckDuckGoSearchRun
search= DuckDuckGoSearchRun()
search_results = search.invoke("History of Alluri Sita Rama Raju?")

# Initialize LLM (e.g., OpenAI's GPT-4)
llm = ChatOpenAI(model="gpt-4", api_key = "********************")

from langchain.chains import LLMChain
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate


# Create a prompt template
prompt = PromptTemplate(input_variables=["query"], template="Summarize the following search results: {query}")

# Create a chain
chain = LLMChain(llm=llm, prompt=prompt)

# process the results with LLM SEarched from DUCKDUCKGO
response = chain.run(search_results)

print(search_results)

print(response)