# -*- coding: utf-8 -*-
"""agent_groq_usage_opensource.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VGjUNtLt2h8IPR0xu2pyQqQh7lcnSj8
"""

!pip install phidata

!pip install Groq

from phi.agent import Agent

groq_api_key="*****************"

from phi.model.groq import Groq

agent = Agent(
    # model = Groq(id="llama-3.1-8b-instant", api_key=)
    model = Groq(id="deepseek-r1-distill-llama-70b", api_key=groq_api_key)
)

# qwen-2.5-32b
# distil-whisper-large-v3-en
# gemma2-9b-it
# llama-3.3-70b-versatile
# llama-3.1-8b-instant
# llama-guard-3-8b
# llama3-70b-8192
# llama3-8b-8192
# mixtral-8x7b-32768
# whisper-large-v3
# whisper-large-v3-turbo

res = agent.print_response("Write a Poem on Pawan kalyan and CHiranjeevi?")

agent.print_response("Compare future of Nifty 50 and Nifty Smallcap for next 20 Years?")

from phi.tools.yfinance import YFinanceTools

agent_tool = Agent(
    model = Groq(id="deepseek-r1-distill-llama-70b", api_key=groq_api_key),
    tools = [YFinanceTools(stock_price=True, analyst_recommendations=True, stock_fundamentals=True)],
    show_tool_calls=True,
    markdown=True,
    instructions=["use Tables to display Data"],
    debug_mode=True

)

agent_tool.print_response("Compare future of Nifty 50 and Nifty Smallcap for next 20 Years?")

agent_tool.print_response("Compare TCS and Infy fundamentals?")

from phi.tools.calculator import Calculator

agent_tool = Agent(
    model = Groq(id="deepseek-r1-distill-llama-70b", api_key=groq_api_key),
    # tools = [YFinanceTools(stock_price=True, analyst_recommendations=True, stock_fundamentals=True)],
    tools = [Calculator(enable_all=True)],
    show_tool_calls=True,
    markdown=True,
    instructions=["Response should be answer only. Dont add extra output"],
    debug_mode=True

)

agent_tool.print_response("What 23+45*2-13+4/2")

agentmath_tool = Agent(
    model = Groq(id="deepseek-r1-distill-llama-70b", api_key=groq_api_key),
    tools = [YFinanceTools(stock_price=True, analyst_recommendations=True, stock_fundamentals=True), Calculator(enable_all=True)],
    show_tool_calls=True,
    markdown=True,
    instructions=["Response should be answer only. Dont add extra output"],
    debug_mode=True
)

agentmath_tool.print_response("What is the Todays stock price difference between TESLA and AAPL?")

agentmath_tool.model

### Create Tools

def get_company_symbols(company: str) -> str:
  """Get the symbol for a company."""
  symb_dict={
      "t" : "TCS",
      "m" : "META"
  }
  return symb_dict.get(company)

from phi.model.openai import OpenAIChat

agent_custom_tool = Agent(
    # model = Groq(id="deepseek-r1-distill-llama-70b",
    #              api_key=groq_api_key),
    model = OpenAIChat(id = "gpt-4o", api_key=open_api_key),
    tools = [get_company_symbols, YFinanceTools(stock_price=True, analyst_recommendations=True, stock_fundamentals=True), Calculator(enable_all=True), ],
    show_tool_calls=True,
    markdown=True,
    instructions=["Response should be answer only. Dont add extra output", "If stock is not available in YFinanceTools use get_company_symbols tool"],
    debug_mode=True
)

agent_custom_tool.print_response("What is the Todays stock price difference between t and m?")